version: '2'
volumes: 
  node-red-data:
  ssh-data:
services:
  node-red:
    build: ./node-red
    ports:
      - '1880:1880'
    volumes: 
      - 'node-red-data:/data'
    working_dir: /data
  ssh:
    build: ./ssh
    ports:
      - '22:22'
    volumes: 
      - 'node-red-data:/data'
      - 'ssh-data:/root/.ssh'
    working_dir: /data