version: '2.1'

volumes: 
  node-red-data:
  mosquitto-config:
  mosquitto-data:
  hue2mqtt-data:
  ssh-data:
  
services:

  node-red:
    build: ./node-red
    ports:
      - '80:1880'
    volumes:
      - 'node-red-data:/data'

  mosquitto:
    image: mbixtech/arm32v7-mosquitto
    ports:
      - '1883:1883'
    volumes:
      - 'mosquitto-config:/mosquitto/config'
      - 'mosquitto-data:/mosquitto/data'

  hue2mqtt:
    build: ./hue2mqtt
    volumes:
      - 'hue2mqtt-data:/root/.hue2mqtt'

  ssh:
    build: ./ssh
    ports:
      - '22:22'
    volumes:
      - 'ssh-data:/root/.ssh'
      - 'node-red-data:/data'

  cloud9:
    build: ./cloud9
    ports:
      - '8080:8080'
    volumes:
      - 'ssh-data:/root/.ssh'
      - 'node-red-data:/data'

