version: '2.1'

volumes: 
  node-red-data:
  mosquitto-data:
  hue2mqtt-config:
  cloud9-workspace:
  ssh-data:
  
services:

  node-red:
    build: ./node-red
    ports:
      - '80:1880'
    volumes:
      - 'node-red-data:/data'

  mosquitto: 
    image: reverie/arm32v7-mosquitto
    ports:
      - '1883:1883'
    volumes:
      - 'mosquitto-data:/etc/mosquitto'

  hue2mqtt:
    build: ./hue2mqtt
    volumes:
      - 'hue2mqtt-config:/root/.hue2mqtt'

  ssh:
    image: klutchell/resin-ssh
    ports:
      - '22:22'
    volumes:
      - 'ssh-data:/root/.ssh'
      - 'cloud9-workspace:/cloud9-workspace'
      - 'node-red-data:/node-red-data'
      - 'mosquitto-data:/mosquitto-data'

  cloud9:
    image: klutchell/resin-cloud9
    ports:
      - '8080:8080'
    volumes:
      - 'ssh-data:/root/.ssh'
      - 'cloud9-workspace:/cloud9-workspace'
      - 'node-red-data:/node-red-data'
      - 'mosquitto-data:/mosquitto-data'

